language: java
jdk:
- oraclejdk8

script: "mvn deploy --settings settings.xml"
env:
  global:
  - secure: "KZmkrF5X0P+rVc25Y2P7RUXgTfwHqjPbw8Zfcod/4KQDMzWtAPpsGlE8kulr1ry0ozRgqyAqTrzf1yRR5YxWgJQOy1rEpWsJ0Jfy1zv7nejsAZX4pT1YsiNrZBJNT9fDdOPOYQm9Fm4C2s0tJPamOgCHbbWJs9EscdcKlnHKyU0bKRT7NIlDraCOBMDiw7S1BG8YCZQJ4Au6jhXyJuGYF8+HNg07cPspI9g/VUEFSmBMisDnB/4zLXy55VMMbH7OcMU4c362JGtwYPQjX5HnbR4JsxtxxI0lOBoUDkY77MwsWlQmruwsPn8e00jO1xNkcuFYohzZklUTRZZDENVFtOeA++DXiaeJzRhZBX56eAZopFe0dPWGfYNRkC+dN4g4GY96aInK/Jxpkg9R/DRwBlhTNoJXFoMVkbIPTn/sEXaa7Ea5S475iQpzhuPFR06Tr26JT39e0ycVB37QIprRsL2mQIJ3pMlK8HcZNnDmg6usESLCHPmgSpfkH9KDGrM14fJ6u0Hl6jmAmvV/iqQWynIA0Be3fIjGQ1fyRhBghj+5SUO1Ux28z5TP+B5yXTssf3zK2dCIac6IRHW43math9hY+lS+6bpcsfhyOF7olbKZB1C5PJT7cRByK6PmPC2hQzn9pyYSQbgvHeZaL5KrxCSpNqNPfbYOprake2nobH4="
  - secure: "mnEM2tBdQjDwEBud/3UGpuD6uuma9ytXaL3YWc44ThwjCa5fgs16gh6TXriJ7ZuPJHtwUaTwB93nFJcwPon9/iofGuY5P5aYAbPvSxPvA8qFSwL3hOziQaf7SxePjRPHctlPrBEGYDVEN9NXkdK/nSqRL7ZljYCp6FtiIzEu8QxDSZm0Us6m7QHzGHpAvCaeDpYAoq/6oKtr3Rgf8sQzCDSdvMvFnDGxVc1sM9kULhzSqBubUZkHYg1VrtJ/KjuwQsDFh8iXuXvPqki3hWBtjaXie2vXBlAH1xiKlX1YgycoBeoQMknGrm6WaB3v0IDEGCAzPAlRdgshuWIhXhaNhSVt1YV2LsXCTWSq3MFI0DWrGj134Kw1LVvbTmN8+JRFrzY9a0+zP91Vpi12hKprmf+qWV6zmfTZe47+L8E7zQFI2zCM/VEWKb9HLJZMrZBJqjR13I3rbwA6nrtuv5ZNcrQ3re5xy807U8LkM+2LQzgqNsb6ihkZhPycNqWKEWtjk/TCzsTBPghk6/Krap8XvVOU/MHOpLDIGe3GCfGfG7GFfu3V/iE74TpcO0nbwp3wIfh1qk/JNENpv1/Pc5qx0CZ84ly7gRmmYVtP9ff+9dRk1FzZtQhR/oiMPrqbJxwnP140vrarXQJZIOCJtILjEosi9xSddibTkKRgTu6XGd4="
before_deploy:
  - export BUKKIT_RELASE_FILE=$(find . -name bukkit-*.jar)
  - export BUNGEE_RELASE_FILE=$(find . -name bungee-*.jar)
deploy:
  provider: releases
  api_key: 
    secure: "n92GsrXFaX5cbChvKyhE6KvR8nFeGuNu7p2Mn/LRAxXtXEbWh9XwBjrZq3xSuSnzFgp0D1J3PBVeWU9MtAmoPlVoSuavqZiuDyzFDAQV8mgn+WFEOfPsMHUcZAIMH6yRTwqBqMBx5zQ+B7aNKLfhFkMOommg9u96sCpNThZ51oCAvCX4wcVWQGeeBTnhMpaGchVIho8qmFSxbHsozqGqvq45R24eGoNiFdEMQuXZIMeXqz/1afhikMpt6jt7ZiulDSLmeJe8qGJBjccWJfGLof87QWebdHxCNLs6VzIlDcqe/tU4Umu4vpMk8zQDXqp4leyUhWj1BHeFzAvPcPmJzdrWzBWHoBUj/dNoemnyQdcfrpeatXrxp/PK2KG2I/S+mELPqM9defr6nBCbNXYTx1VX4R+q8UPD/vlrPfJFTqV6Uh44aTetdscPbNYhT553eHR7C/XXaGntPk9joHtQTzlLcqET75quJ7KEzGozfg9liHWEJ8ND4o/qlFkQ7r9AvTtRm9mVp6azoC6HOWtiXXm/qMn8Jtk7qQ/3YSgfLk3A54nQcfVZFLJwFdMUaAIIZ2XZ6Rqq77sTSuc1tvshni61HqZpCvgEC9Uo2xGiczE8rEtbtXy+6zgyOiaMqCan9GIiKqqoD8BB91JBfwPN4q2C5m/iR/4YXENPhDQUtlk="
  file_glob: true
  file: 
    - "Bukkit/target/bukkit-*.jar"
    - "Bungee/target/bungee-*.jar"
  skip_cleanup: true
  on:
    tags: true
