language: java
jdk:
- oraclejdk8

script: "mvn javadoc:aggregate deploy --settings settings.xml"
before_script:
  - "chmod +x .script/upload-javadoc.sh"
after_success: ".script/upload-javadoc.sh"
env:
  global:
  - secure: "KZmkrF5X0P+rVc25Y2P7RUXgTfwHqjPbw8Zfcod/4KQDMzWtAPpsGlE8kulr1ry0ozRgqyAqTrzf1yRR5YxWgJQOy1rEpWsJ0Jfy1zv7nejsAZX4pT1YsiNrZBJNT9fDdOPOYQm9Fm4C2s0tJPamOgCHbbWJs9EscdcKlnHKyU0bKRT7NIlDraCOBMDiw7S1BG8YCZQJ4Au6jhXyJuGYF8+HNg07cPspI9g/VUEFSmBMisDnB/4zLXy55VMMbH7OcMU4c362JGtwYPQjX5HnbR4JsxtxxI0lOBoUDkY77MwsWlQmruwsPn8e00jO1xNkcuFYohzZklUTRZZDENVFtOeA++DXiaeJzRhZBX56eAZopFe0dPWGfYNRkC+dN4g4GY96aInK/Jxpkg9R/DRwBlhTNoJXFoMVkbIPTn/sEXaa7Ea5S475iQpzhuPFR06Tr26JT39e0ycVB37QIprRsL2mQIJ3pMlK8HcZNnDmg6usESLCHPmgSpfkH9KDGrM14fJ6u0Hl6jmAmvV/iqQWynIA0Be3fIjGQ1fyRhBghj+5SUO1Ux28z5TP+B5yXTssf3zK2dCIac6IRHW43math9hY+lS+6bpcsfhyOF7olbKZB1C5PJT7cRByK6PmPC2hQzn9pyYSQbgvHeZaL5KrxCSpNqNPfbYOprake2nobH4="
  - secure: "mnEM2tBdQjDwEBud/3UGpuD6uuma9ytXaL3YWc44ThwjCa5fgs16gh6TXriJ7ZuPJHtwUaTwB93nFJcwPon9/iofGuY5P5aYAbPvSxPvA8qFSwL3hOziQaf7SxePjRPHctlPrBEGYDVEN9NXkdK/nSqRL7ZljYCp6FtiIzEu8QxDSZm0Us6m7QHzGHpAvCaeDpYAoq/6oKtr3Rgf8sQzCDSdvMvFnDGxVc1sM9kULhzSqBubUZkHYg1VrtJ/KjuwQsDFh8iXuXvPqki3hWBtjaXie2vXBlAH1xiKlX1YgycoBeoQMknGrm6WaB3v0IDEGCAzPAlRdgshuWIhXhaNhSVt1YV2LsXCTWSq3MFI0DWrGj134Kw1LVvbTmN8+JRFrzY9a0+zP91Vpi12hKprmf+qWV6zmfTZe47+L8E7zQFI2zCM/VEWKb9HLJZMrZBJqjR13I3rbwA6nrtuv5ZNcrQ3re5xy807U8LkM+2LQzgqNsb6ihkZhPycNqWKEWtjk/TCzsTBPghk6/Krap8XvVOU/MHOpLDIGe3GCfGfG7GFfu3V/iE74TpcO0nbwp3wIfh1qk/JNENpv1/Pc5qx0CZ84ly7gRmmYVtP9ff+9dRk1FzZtQhR/oiMPrqbJxwnP140vrarXQJZIOCJtILjEosi9xSddibTkKRgTu6XGd4="
  - secure: "AhSYOwdwz4hhsopVCYyTyfwni4Hnu4CbLY2BVN6mYnKj/gGLPh+215cv4CQUSGhu8VEBz5AXs7zw/NrbXY0M7D7zCngiqAUSWAG2cvspKIMgwwiKMAn8hheNmwlmdFuiR4kRujoRByoaCp+yvHbYviggTKm6RZXN3jdqbp5kO4dgZD8qZM8JGKk0CA6bein0FrFWVeRNygAISFBn54vEFxeOWZTI3c0XzouaHsYJYfVt0fwOlIaexP0rZXOckXoCku9KzCcmEdeWMov2D5Cm9tJxp02FyK63HD2AuB+fKs62mrRwvmBgQoQx/LLsuKegPbCkj1ym9/y5hS6gLBA8C6q/ZadiRO6mmS7u8QNvM+bZCDeN8p3H81+P5dhUL8LJu91tDMlZo8e+AQyTbOvfQUIqDXCZQMAd20qjuNaucH6P4zXHCaYSTC4E4uPhAvGsZ6op0/Zg0vS6Yg4F+GnGEUMA/JKGLwXU3w7ZE3NXIf2MoM6urXgwU9x5Pt4Twjsc4Q33bs9VAlSvoUSzH0aStBmZ+G0E9NyxNg4LyEDtJtpZ/6te683c3sNCOFft/PfrFh0na0njPpEnSanrHXCrr0IlLfyXimXFkODUtD4BYpH+arlWWCaZgaNGmTsTq8/LQhlo40SRVA+z5dXJ6ckcDfBm7ROwc4NcFndGz0bhcPs="
before_deploy:
  - export BUKKIT_RELASE_FILE=$(find . -name bukkit-*.jar)
  - export BUNGEE_RELASE_FILE=$(find . -name bungee-*.jar)
deploy:
  provider: releases
  api_key: 
    secure: "UWtRa2e6zn0A211KhsMR1zBve3+JN3UykcUXkB9ZFz9zREZUKgBqfxwKGpSCIbGZO5lEhMExAi5Ek7R3XTYLB5HSq+HodFQvYjQoinxF/MzKwDP2biXevp36hmICl+WPGdh0fovw4dDcJ2JFN3CQHYNgnabbelWkReda3hHuKqWWxG3mBR9mCG2y4NyneYtum82kq10os/AJNmDgmtDE+yYDdoP0o0yr8RtKmtArkBCxjD0PZlZcB5arAv3NCtmZ+eZM9m3DR7WOXrJv08JJmwV3KlBE7P8qGDfCh5I/AjlJZPR3epR8zWkTvu/D9jjQiWkNpTvRsTrkzb1+xeMdotmOV/d1YTpjNAg47nhkIOx/DXfK+pCEQcQEmPNWdm8TCix+BhULkGxDkH2dZjrsP8xBecHQlhYqRDaH16VUxvSKqatLelsg02uK8IrYvty1VJSUp7BxypPUkDjz1ae7w+MXZwX33Dyzq2SlH6Yz6WZ5TADxKsy/n4w5g6LbRlCnlH0fQQIXOy58XJYrlyguFLF1yxgca8Q17PvmfF8h2x4CXi9RTpcYPKduvGlPF3rqlK9kI0tgKHToRTRVvEtvL2fJLTyiGmB/QMEQ1abNon/osiah3QxbD96k44V7YU9njYUuHkpd2pj6afPFqI1uklBuApe7IMCB8Gc8LJ/iDhA="
  file_glob: true
  file: 
    - "Bukkit/target/bukkit-*.jar"
    - "Bungee/target/bungee-*.jar"
  skip_cleanup: true
  on:
    tags: true
