language: java
jdk:
- oraclejdk8

script: "mvn deploy --settings settings.xml"
env:
  global:
  - secure: "KZmkrF5X0P+rVc25Y2P7RUXgTfwHqjPbw8Zfcod/4KQDMzWtAPpsGlE8kulr1ry0ozRgqyAqTrzf1yRR5YxWgJQOy1rEpWsJ0Jfy1zv7nejsAZX4pT1YsiNrZBJNT9fDdOPOYQm9Fm4C2s0tJPamOgCHbbWJs9EscdcKlnHKyU0bKRT7NIlDraCOBMDiw7S1BG8YCZQJ4Au6jhXyJuGYF8+HNg07cPspI9g/VUEFSmBMisDnB/4zLXy55VMMbH7OcMU4c362JGtwYPQjX5HnbR4JsxtxxI0lOBoUDkY77MwsWlQmruwsPn8e00jO1xNkcuFYohzZklUTRZZDENVFtOeA++DXiaeJzRhZBX56eAZopFe0dPWGfYNRkC+dN4g4GY96aInK/Jxpkg9R/DRwBlhTNoJXFoMVkbIPTn/sEXaa7Ea5S475iQpzhuPFR06Tr26JT39e0ycVB37QIprRsL2mQIJ3pMlK8HcZNnDmg6usESLCHPmgSpfkH9KDGrM14fJ6u0Hl6jmAmvV/iqQWynIA0Be3fIjGQ1fyRhBghj+5SUO1Ux28z5TP+B5yXTssf3zK2dCIac6IRHW43math9hY+lS+6bpcsfhyOF7olbKZB1C5PJT7cRByK6PmPC2hQzn9pyYSQbgvHeZaL5KrxCSpNqNPfbYOprake2nobH4="
  - secure: "mnEM2tBdQjDwEBud/3UGpuD6uuma9ytXaL3YWc44ThwjCa5fgs16gh6TXriJ7ZuPJHtwUaTwB93nFJcwPon9/iofGuY5P5aYAbPvSxPvA8qFSwL3hOziQaf7SxePjRPHctlPrBEGYDVEN9NXkdK/nSqRL7ZljYCp6FtiIzEu8QxDSZm0Us6m7QHzGHpAvCaeDpYAoq/6oKtr3Rgf8sQzCDSdvMvFnDGxVc1sM9kULhzSqBubUZkHYg1VrtJ/KjuwQsDFh8iXuXvPqki3hWBtjaXie2vXBlAH1xiKlX1YgycoBeoQMknGrm6WaB3v0IDEGCAzPAlRdgshuWIhXhaNhSVt1YV2LsXCTWSq3MFI0DWrGj134Kw1LVvbTmN8+JRFrzY9a0+zP91Vpi12hKprmf+qWV6zmfTZe47+L8E7zQFI2zCM/VEWKb9HLJZMrZBJqjR13I3rbwA6nrtuv5ZNcrQ3re5xy807U8LkM+2LQzgqNsb6ihkZhPycNqWKEWtjk/TCzsTBPghk6/Krap8XvVOU/MHOpLDIGe3GCfGfG7GFfu3V/iE74TpcO0nbwp3wIfh1qk/JNENpv1/Pc5qx0CZ84ly7gRmmYVtP9ff+9dRk1FzZtQhR/oiMPrqbJxwnP140vrarXQJZIOCJtILjEosi9xSddibTkKRgTu6XGd4="
before_deploy:
  - export BUKKIT_RELASE_FILE=$(find . -name bukkit-*.jar)
  - export BUNGEE_RELASE_FILE=$(find . -name bungee-*.jar)
deploy:
  provider: releases
  api_key: 
    secure: "M0ifOSZjy77cI7/gzK8eZlkRm0JXJekEjc8VHg/TEC4XtC0xNPaIuBG10nbWSgW0N++kqJ8JRZwHGokjktkyKCkewWpLyzUF0Q//bd0E59UxuF0y5MljWVFick8f7OiEkfDkbo3cpMusakjRHnByU7bAR2yuAMeCGFKHjX+y9SGyEVdG2uj1x3IERP4m/2XR5D1LlFDXDYyoGKTNT7gyfxJIyob5JR9Jh9m6LTh04QQJy8rP6f6Mq9VNA3QoBi6on6Hu3tYFrpF3l3zWKux4P4EQqgl8wy7gaNrsFVReETnd+SVwdTfjtzdoegK0F9mZKTJFpTZkrc8qhHoXFdwJEymLK2FLZc0HgOcNLSuOLdRKgoczUjNu4U50/fJMZLrjEQEQw4wCWsALj4fMWaDFKwd2hRE+Hhv7cfaza5TqSiYKwTM2IH01UFIi95pJe2MRxE1Q+Uhb77a+E1KrE4SGulqDqZ/qQcCzYGNjMQRpVLWyEbwML08VZxUFK6eUaCD6Ayd1ybx2SX5Lu/3biFm+e4pk/qLV750jW49OHBI/Ubvh2dmCQzFWsP5ck7bw+dGInYw2EFkiZOYL6q3Ddsx0IGd2llWws4zQwKcIycIHyd4rPulVsV03eZwPkSY6659xxgLFQQ5XZkGcAje+ePNyp8GJt4PxUZte/GfkgCnZB04="
  file_glob: true
  file: 
    - "Bukkit/target/bukkit-*.jar"
    - "Bungee/target/bungee-*.jar"
  skip_cleanup: true
  on:
    tags: true
